fail_fast: false

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: format
    name: Format
    entry: make format
    types: [python]
    language: system
    pass_filenames: false
  - id: mypy
    name: Mypy
    entry: make mypy
    types: [python]
    language: system
    pass_filenames: false
