language: python

cache: pip

services:
- redis-server

matrix:
  include:
  - python: '3.7'
    dist: xenial
    sudo: required
  - python: 3.8-dev
    dist: xenial
    sudo: required

  allow_failures:
  - python: 3.8-dev

install:
- make install

script:
- make lint
- make test
- make docs
- ./tests/check_tag.py

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)

env:
- secure: "FlvWpK0GHTDeSxm6FHIIVmn7k75blN1rvjRR9vFlJcgsvz9ay+NZX4DKQCftNkA5bwMDS05Dlr3BTVROAojwv/qfBPKPFRtDEvTiYN8uQWPTqPw4pVu9OuXQKV+JwRFTsg4wsCe4wi7Gb82Z6ho3N5AJpwk8sasZtBR62GuQY+utSUXBRldCqmBA5NuApa3DTpS1+6jKWOU4jtM8mrssDTPmTEk3vcfqGWr/6QdIPTYZRIJHI7NZ+FYVM0s/KOn7T4gqNuB7CLnHdf9836lyCKobfLFiO5HSSig+qwUfXKRbN7/FP/kwtur4N7qUDPolROFWtCo7l6dTEPV7yNAzt+Jk49HnxxyAEVubnsh2EJGBPbWRX41Pzmld+ld5/JqvONgvSBQDTXpOgRfYSkxRn29SQ7P+ofGVRm2KglbUTzbal3tAZTODsLpaDFrzkNfp7sQJiR33wzNbFaF7pzJZqg9MxD7SY1QiCSc5WkdPavyTKgVUQwCxdywQ0d+/gEBVxQL9bYno2zO4zcWxV93ChxQIZCE3LR9wFRn3u/DvLlHjJ2m1IRoyv6AzeF/D1c9uOsdDcRJCJhuJcoL6EuLlsbKQVHcQga6+E85zkSacsRmCwVFWtFbOovm1Y5hBZtZxm84wkOTSHVYNxIge1hbpKvg+D6dmUjo5yrjnYVEA/II="

deploy:
- provider: pypi
  user: samuelcolvin
  password:
    secure: fM1AEWtweEM0JMJET4ONgbk0E3FlPo0A4lymNRj+iKBAG1qhYtR+jJNtYCAnTbL0RZJjxofIP1vnDOW/xukAzh8stDjc199Gr2uqVox3xH6LplK75Ouc8QpEhYKg4r3y58m+9cp0H10OBNsUV3pTJe52KQFfT+C1e+rA1zKk0t1QbUiBaXyRweqNLfS1K+Bfb9dXtbKE66KV8TXKS4HXrsjBU3I4OlgDOSC2JCOivPUCBwVsN8OW4MDLt8gEuK+i5JkN0hBEBR3LGSi8n8CU+32fXDpl0RVmYbIR3CbgDVx79HKZIWSYbFJ+JRDpKIio0H0bvgpy1hI92olS4K0ExI3Y2S/gToGMA+jdZdjQgobCoDor3kGaG2ZzT/iG2IzB4pnNjrwQhEzVGQMrXBxiWT8Yw1I+lanV88U57x2A8/RmTzMPMu5bK0QCFBPZ9cOUA7lmFpG2lJvYnK/kdjIE4/RX1LGfKgPs7i2dM+yj7jSUuVUQY+Y0Ja5I11GsAzMpKtH1HnN9dQ0n0rfE+Le4ATdVA9lj2te4v/csrC/wiC5n4mg1YIGxDU0obEvtiNepK4suCsy/PDLiHx5xzIS0z7WWhHK+6XCBDC5enw+2hKs3ETJW3KbDU0Mz3q8vV64VObxZPLQxfKgT5o30OyMElsnLIZhK4R2Vsr5CzRzP2pY=
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    tags: true
    python: 3.7
- provider: script
  script: make deploy-docs
  on:
    tags: true
    python: 3.7
