language: python

cache: pip

services:
- redis-server

python:
- '3.6'
- '3.6-dev'
- 'nightly'

matrix:
  allow_failures:
  - python: '3.6-dev'
  - python: 'nightly'

install:
- make install

script:
- make lint
- make test
- make docs
- ./tests/check_tag.py
